/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cosmolustosa.br.controle_de_frotas;

import java.awt.Font;
import com.cosmolustosa.br.db.ConectaDB;
import java.awt.Dialog;

/**
 *
 * @author Cosmo Lustosa
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setFont(Font.getFont("Roboto"));
        this.setLocationRelativeTo(null); //coloca a janela no centro da tela
        this.menuCadastro.setMnemonic('o');
        this.menuRelatorio.setMnemonic('r');
        //this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        bt_cadastrar = new javax.swing.JButton();
        bt_veiculo = new javax.swing.JButton();
        bt_relatorio = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuPessoa = new javax.swing.JMenuItem();
        jMenuItemVeiculo = new javax.swing.JMenuItem();
        jMenuItemFilial = new javax.swing.JMenuItem();
        jMenuItemCombustivel = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menuConfiguracoes = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Viagens");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Prinicipal"); // NOI18N

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        bt_cadastrar.setBackground(new java.awt.Color(244, 244, 244));
        bt_cadastrar.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        bt_cadastrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cosmo Lustosa\\Documents\\NetBeansProjects\\controle_de_frotas\\src\\main\\java\\com\\cosmolustosa\\br\\controle_de_frotas\\imgs\\add.png")); // NOI18N
        bt_cadastrar.setText("Cadastrar");
        bt_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_cadastrar);

        bt_veiculo.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        bt_veiculo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cosmo Lustosa\\Documents\\NetBeansProjects\\controle_de_frotas\\src\\main\\java\\com\\cosmolustosa\\br\\controle_de_frotas\\imgs\\carro.png")); // NOI18N
        bt_veiculo.setText("Veículos");
        bt_veiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_veiculoActionPerformed(evt);
            }
        });
        jPanel1.add(bt_veiculo);

        bt_relatorio.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        bt_relatorio.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cosmo Lustosa\\Documents\\NetBeansProjects\\controle_de_frotas\\src\\main\\java\\com\\cosmolustosa\\br\\controle_de_frotas\\imgs\\relatorio.png")); // NOI18N
        bt_relatorio.setText("Relatórios");
        bt_relatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(bt_relatorio);

        jButton5.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jButton5.setText("jButton5");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton5);

        jButton13.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jButton13.setText("jButton13");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton13);

        jButton12.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jButton12.setText("jButton12");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton12);

        jButton11.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jButton11.setText("jButton11");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton11);

        menuCadastro.setText("Cadastro");
        menuCadastro.setToolTipText("Cadastro Alt+O");
        menuCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCadastro.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        menuPessoa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuPessoa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cosmo Lustosa\\Documents\\NetBeansProjects\\controle_de_frotas\\src\\main\\java\\com\\cosmolustosa\\br\\controle_de_frotas\\imgs\\pessoas.png")); // NOI18N
        menuPessoa.setText("Pessoas");
        menuPessoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPessoaActionPerformed(evt);
            }
        });
        menuCadastro.add(menuPessoa);

        jMenuItemVeiculo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemVeiculo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cosmo Lustosa\\Documents\\NetBeansProjects\\controle_de_frotas\\src\\main\\java\\com\\cosmolustosa\\br\\controle_de_frotas\\imgs\\veiculo32.png")); // NOI18N
        jMenuItemVeiculo.setText("Veículo");
        jMenuItemVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCadastro.add(jMenuItemVeiculo);

        jMenuItemFilial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemFilial.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cosmo Lustosa\\Documents\\NetBeansProjects\\controle_de_frotas\\src\\main\\java\\com\\cosmolustosa\\br\\controle_de_frotas\\imgs\\32\\filial.png")); // NOI18N
        jMenuItemFilial.setText("Filial");
        jMenuItemFilial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFilialActionPerformed(evt);
            }
        });
        menuCadastro.add(jMenuItemFilial);

        jMenuItemCombustivel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemCombustivel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cosmo Lustosa\\Documents\\NetBeansProjects\\controle_de_frotas\\src\\main\\java\\com\\cosmolustosa\\br\\controle_de_frotas\\imgs\\32\\combustivel32.png")); // NOI18N
        jMenuItemCombustivel.setText("Combustível");
        jMenuItemCombustivel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCombustivelActionPerformed(evt);
            }
        });
        menuCadastro.add(jMenuItemCombustivel);

        jMenuBar1.add(menuCadastro);

        menuRelatorio.setText("Relatórios");
        menuRelatorio.setToolTipText("Relatórios Alt+R");
        menuRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRelatorio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jMenuBar1.add(menuRelatorio);

        menuConfiguracoes.setMnemonic('f');
        menuConfiguracoes.setText("Configurações");
        menuConfiguracoes.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jMenuBar1.add(menuConfiguracoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCombustivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCombustivelActionPerformed

    private void menuPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPessoaActionPerformed
        // TODO add your handling code here:
       PessoaForm pf =  new PessoaForm();
       pf.setVisible(true);
       pf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuPessoaActionPerformed

    private void jMenuItemFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFilialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemFilialActionPerformed

    private void bt_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarActionPerformed
        // TODO add your handling code here:
        ConectaDB.abreConexao();
    }//GEN-LAST:event_bt_cadastrarActionPerformed

    private void bt_veiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_veiculoActionPerformed
       VeiculoForms vf = new VeiculoForms(this, true);
       vf.setLocationRelativeTo(null);//centraliza a janela
       vf.setVisible(true);
    }//GEN-LAST:event_bt_veiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cadastrar;
    private javax.swing.JButton bt_relatorio;
    private javax.swing.JButton bt_veiculo;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItemCombustivel;
    private javax.swing.JMenuItem jMenuItemFilial;
    private javax.swing.JMenuItem jMenuItemVeiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuConfiguracoes;
    private javax.swing.JMenuItem menuPessoa;
    private javax.swing.JMenu menuRelatorio;
    // End of variables declaration//GEN-END:variables
}
